/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodePreview: typeof import('./.vitepress/components/demos/sort-script-setup/code-preview.vue')['default']
    CustomWrapper: typeof import('./.vitepress/components/CustomWrapper.vue')['default']
    SortScriptSetup: typeof import('./.vitepress/components/demos/sort-script-setup/index.vue')['default']
  }
}
